name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "Swk5-rocks!"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "sqlcmd -S localhost -U sa -P Swk5-rocks! -Q 'SELECT 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore

      - name: Apply database schema
        run: |
          docker cp ./init-db.sql $(docker ps -q --filter "ancestor=mcr.microsoft.com/mssql/server:2022-latest"):/init-db.sql
          docker exec $(docker ps -q --filter "ancestor=mcr.microsoft.com/mssql/server:2022-latest") /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Swk5-rocks! -i /init-db.sql

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
